id: I62247B62
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T19:37:40+00:00'
last_modified: '2022-06-08T07:15:32.623938+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23917
  title: ཤངས་པ་བཀའ་བརྒྱུད་པའི་ཁྲིད་སྐོར་ཐང་རྒྱལ་ལུགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BDFE:
      image_group_id: I3516
      title: ''
      total_pages: 520
      order: 1
      base_file: BDFE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
